### ISSUE TITLE
Should the indices field be named values?

### ISSUE THREAD

**Issue by dmbates** [nalimilan/CategoricalArrays.jl#1]
If I understand correctly the `values` field is the numeric indices into the `pool`.  I would think that a name such as `refs` or `indices` or `indexes` would be more appropriate.  In most types a field name of `values` indicates the actual values in the type without the metadata.

**Comment by dmbates** [comment]
By the way, thanks for all the work on this, @nalimilan.  I should have said that before making a suggestion of a change.

**Comment by nalimilan** [comment]
Thanks for the feedback. I was thinking of renaming it too. I had chosen `values` because that's what `NullableArray` uses, but there's actually no parallel between these structures.

`refs` has the advantage that it's already used by PDAs. `indices` might be more explicit. Not sure.
