### ISSUE TITLE
Lower-level constructors

### ISSUE THREAD

**Issue by quinnj** [nalimilan/CategoricalArrays.jl#5]
I'm having a hard time figuring out how to construct a CategoricalArray at a "lower level" than just providing a vector of strings + missingness vector.

My use-case is Feather.jl, where the raw file bits provide an actual list of unique levels as strings, a vector of Ints of the actual elements, and an indication of whether the levels are ordered or not. Given these three items, is there some kind of intermediate constructor I could use? Do I need to manually build a Pool first and then use that to build my Array? Any pointers here would be most appreciated.

**Comment by quinnj** [comment]
Oh, Feather.jl also gives us the `null_count`, so theoretically, I think we have all the info we need to choose between the 4 CategoricalArray types.

**Comment by nalimilan** [comment]
I haven't given much attention to low-level constructors yet, but it looks like your use case should work pretty well using the default lowest-level constructor. You indeed need to create a pool manually (these types aren't exported, maybe we should change that) using one of the numerous constructors from `src/pool.jl`. Then you can pass it to the categorical array constructor together with the integer codes. For example:
```julia
pool = NominalPool(["a","b","c"])
refs = UInt32[1, 2, 3]
NominalArray{String,1,UInt32}(refs, pool)
```

I could add a convenience method to avoid the requirement to specify type parameters manually if that's useful.

**Comment by quinnj** [comment]
Awesome. What about Ordered? Anything else that needs to happen? Does the array passed to the pool just need to be ordered?

**Comment by nalimilan** [comment]
You just need to create an `OrderedPool`, which by default will sort the levels in the order you provide them (which will also be the order of the integer codes). If needed, there are also constructors to pass a custom order.

**Comment by quinnj** [comment]
What about Nullable versions? The incantation above doesn't seem to accept a NullableArray as the `refs` argument, and there doesn't seem to be a way of passing a vector of bools.

**Comment by quinnj** [comment]
Oh, I think I figured it out. Build a `NominalArray` first, then do `NullableNominalArray(nom_arr, bools)`

**Comment by nalimilan** [comment]
No, you shouldn't have to build a `NominalArray` first. I've just tested it, and my example from above works fine when using `NullableNominalArray`. Though contrary to the Feather format (which uses a separate bit mask like `NullableArray`), null values are stored directly as `0` in the `refs` field. So you'll have to ensure all nulls have a `0` value. I hope that's practical (for both reading and writing).

(I chose that representation to save some memory while still being fast, since a `BitArray` mask was slower AFAIK in NullableArray explorations, and an `Array{Bool}` mask would use one byte for each 32-bit code, which isn't negligible.)

**Comment by quinnj** [comment]
Ah, got it. One more question, do the array types allow storing in various integer types? I'm having trouble constructing anything but `UInt32`; it seems like the `Pool` constructors force everything else to be UInt32, or maybe I'm just not using it quite right.

**Comment by nalimilan** [comment]
Ah, that's a bit hard to get right. You need to pass the type parameter when building the pool, and then again when building the array:
```julia
pool = NominalPool{String,UInt8}(["a","b","c"])
refs = UInt8[1, 2, 3]
NominalArray{String,1,UInt8}(refs, pool)


```

**Comment by quinnj** [comment]
Got it thanks.

**Comment by nalimilan** [comment]
Great! Is the use of `0` to signal a null a constraint w.r.t. how feather works? Just curious.

**Comment by quinnj** [comment]
No, they have a separate null bitmask that is written before the actual array values. Their factors are actually 0-based, so I do a quick translation for compat here and when writing back. Made for an interesting 15-minute debugging session where everything was really weird :)
