### ISSUE TITLE
Define `push!` and `append!`

### ISSUE THREAD

**Issue by quinnj** [nalimilan/CategoricalArrays.jl#6]
Currently in DataStreams, I'm ironing out an "api" of sorts for columns, i.e. the things that actually store data in a `Source` or `Sink`. They're mainly interacted with through the `Data.getfield` and `Data.getcolumn` methods, but they also need to support a few basic methods. Currently this includes:

* `push!(A, item)`
* `append!(A, B)`
* `setindex!(A, item, i)`
* `allocate{T}(::Type{T}, rows, ref)`

Most of these are pretty basic, though `allocate` is the funny one. `allocate` takes a *scalar* type (i.e. `T`, `Nullable{T}`, `NominalValue{S, R}`), a # of rows, and a potential `ref` or `parent` `Vector{UInt8}` and allocates a new column vector of some kind that the data will be streamed to.

I'm happy to have the `allocate` methods for CategoricalArrays live in DataStreams for now (while things settle down), with the idea that they could eventually move to the various packages (NullableArrays, DataFrames, CategoricalArrays, etc.).

The two we seem to be missing, however, are `push!` and `append!` for the various CategoricalArray types. Happy to take a crack at it, but wanted to post it here first.

**Comment by nalimilan** [comment]
Sure, please feel free to make a PR. (Though on the long term I think it would make sense to define default `push!` and `append!` methods for `AbstractArray` based on `resize!`.)

As regards `allocate`, it's maybe be more logical to have DataStreams implement it. It depends on which package should be considered the most basic. Do we prefer DataStreams to depend on NullableArrays and CategoricalArrays, or the other way round?

**Comment by nalimilan** [comment]
Closed by https://github.com/nalimilan/CategoricalArrays.jl/pull/9?
